import os
import sys
import json
import requests
from dotenv import load_dotenv

load_dotenv()

TRELLO_KEY = os.getenv("TRELLO_KEY")
TRELLO_TOKEN = os.getenv("TRELLO_TOKEN")
TRELLO_LIST_ID = os.getenv("TRELLO_LIST_ID")

if not all([TRELLO_KEY, TRELLO_TOKEN, TRELLO_LIST_ID]):
    raise Exception("Missing Trello environment variables.")


def create_trello_card(name: str, desc: str):
    url = "https://api.trello.com/1/cards"
    params = {
        "key": TRELLO_KEY,
        "token": TRELLO_TOKEN,
        "idList": TRELLO_LIST_ID,
        "name": name,
        "desc": desc,
        "pos": "top"
    }
    r = requests.post(url, params=params)
    if r.status_code >= 300:
        print("Trello API error:", r.status_code, r.text)
        raise Exception("Failed to create Trello card")
    print("Created Trello card:", r.json().get("url"))


def build_card_markdown(d):

    ts = d["timestamp_utc"]

    users = d["users"]
    verified = d["verified"]

    new_user_tweet = d["tweet_users"]
    verified_tweet = d["tweet_verified"]

    # Users section
    users_view = "\n".join(
        f"- {u['name']} ({'@'+u['handle'] if u['handle'] else 'no handle'})"
        for u in users
    )

    # Verified section with method
    verified_view = "\n".join(
        f"- {v['name']} ({'@'+v['handle'] if v['handle'] else 'no handle'}) — {v['method']}"
        for v in verified
    )

    return f"""
**Generated at:** {ts} UTC

---

# 🚀 New to ZcashMe (last 24h)
**Count:** {len(users)}

### 📝 Tweet Preview
{new_user_tweet}

### 👥 New Users
{users_view}

---

# 🔐 Newly Verified (last 24h)
**Count:** {len(verified)}

### 📝 Tweet Preview
{verified_tweet}

### 🔎 Verification Details
{verified_view}

---

This card was automatically generated by the **ZcashMe Promote-Bot**.
Review the two tweet drafts above and publish manually on Twitter.
"""


def main():
    if len(sys.argv) < 2:
        print("Usage: python create_trello_cards.py drafts/daily_combined.json")
        return

    fpath = sys.argv[1]

    with open(fpath, "r", encoding="utf-8") as f:
        data = json.load(f)

    title = f"Daily Promo — Combined — {data['timestamp_utc'][:16]} UTC"
    desc = build_card_markdown(data)

    create_trello_card(title, desc)


if __name__ == "__main__":
    main()
