import os
import sys
import json
import requests
from datetime import datetime
from dotenv import load_dotenv
load_dotenv()



# ---------------------------------------------------------
# Environment setup
# ---------------------------------------------------------
TRELLO_KEY = os.getenv("TRELLO_KEY")
TRELLO_TOKEN = os.getenv("TRELLO_TOKEN")
TRELLO_LIST_ID = os.getenv("TRELLO_LIST_ID")

if not all([TRELLO_KEY, TRELLO_TOKEN, TRELLO_LIST_ID]):
    raise Exception("Missing one of: TRELLO_KEY, TRELLO_TOKEN, TRELLO_LIST_ID")


# ---------------------------------------------------------
# Create Trello Card
# ---------------------------------------------------------
def create_trello_card(name: str, desc: str):
    url = "https://api.trello.com/1/cards"
    params = {
        "key": TRELLO_KEY,
        "token": TRELLO_TOKEN,
        "idList": TRELLO_LIST_ID,
        "name": name,
        "desc": desc,
        "pos": "top"
    }

    r = requests.post(url, params=params)
    if r.status_code >= 300:
        print("Trello API error:", r.status_code, r.text)
        raise Exception("Failed to create Trello card")

    data = r.json()
    print(f"Created Trello card: {data.get('url')}")
    return data


# ---------------------------------------------------------
# Format card markdown
# ---------------------------------------------------------

def build_card_markdown(draft: dict):
    timestamp = draft["timestamp_utc"]
    count = draft["count"]
    tweet = draft["tweet"]

    items = draft["items"]

    items_preview = "\n".join(
        [f"- {i['name']} ({i['handle'] or 'no handle'})" for i in items[:10]]
    )

    if len(items) > 10:
        items_preview += f"\n- ... and {len(items) - 10} more"

    md = f"""**Generated at:** {timestamp}
**Count:** {count}

---

### 📝 Tweet Preview
{tweet}

---

### 👥 Top entries
{items_preview}

---

This card was automatically generated by the ZcashMe Promote-Bot.
Edit the tweet text if needed, then publish manually on Twitter.
"""

    return md


# ---------------------------------------------------------
# MAIN ENTRY
# ---------------------------------------------------------
def main():
    if len(sys.argv) < 2:
        print("Usage: python create_trello_cards.py <file1.json> <file2.json> ...")
        sys.exit(1)

    json_files = sys.argv[1:]
    print(f"Processing {len(json_files)} draft files...")

    for fpath in json_files:
        print(f"Reading {fpath}...")
        with open(fpath, "r", encoding="utf-8") as f:
            draft = json.load(f)

        # Determine card title
        if "new_users" in fpath:
            title = f"Daily Promo — New Users — {draft['timestamp_utc'][:16]} UTC"
        elif "new_verified" in fpath:
            title = f"Daily Promo — New Verifications — {draft['timestamp_utc'][:16]} UTC"
        else:
            title = f"Daily Promo — {os.path.basename(fpath)}"

        desc = build_card_markdown(draft)

        # Create Trello card
        create_trello_card(title, desc)

    print("All Trello cards created!")


if __name__ == "__main__":
    main()
